// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQcSyWcjqc-RxofjQ4OqpxQ42bU1VbShc',
    appId: '1:703462473125:web:2ab15732bb18b7e76e3c4c',
    messagingSenderId: '703462473125',
    projectId: 'allergi-d4361',
    authDomain: 'allergi-d4361.firebaseapp.com',
    storageBucket: 'allergi-d4361.firebasestorage.app',
    measurementId: 'G-SZW4WQLEBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqEwoC9sTbiDc9USYOMjil8elEcH3S9SA',
    appId: '1:703462473125:android:15d28d1f349cb2716e3c4c',
    messagingSenderId: '703462473125',
    projectId: 'allergi-d4361',
    storageBucket: 'allergi-d4361.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2IUVuMgZ-jD04tdDdOWLTGMU9SmiGMEs',
    appId: '1:703462473125:ios:91461025d852bc5c6e3c4c',
    messagingSenderId: '703462473125',
    projectId: 'allergi-d4361',
    storageBucket: 'allergi-d4361.firebasestorage.app',
    iosBundleId: 'com.allergi.allergi',
  );
}
